# vim: set ft=toml ts=2 sw=2 sts=2 et:
#
# This is a configuration for chore. A configuration language is TOMl
#
# https://toml.io/en/
# https://github.com/9seconds/chore

# vault is a mapping for namespace name to a password for a
# secret vault that is used for that namespace
[vault]
{{- range $name, $password := .Vault }}
# {{ $name }} = "{{ $password }}"
{{- end }}
